### ISSUE TITLE
Mode of transportation in DFH:customer

### ISSUE THREAD

**Issue by cherry-pn** [kennCK/tinabangay_app#20]
Dli mo gana ang dropdown para sa mode of transportation  sa Health Declaration form sa mobile same sad sa pag select og gender d sad cia mo gana
![image](https://user-images.githubusercontent.com/54086808/89493690-4c8dcc80-d7e7-11ea-9f65-5ab55e1ff117.png)

**Comment by kennCK** [comment]
This is fixed on version 3.0
