### ISSUE TITLE
Log-out tab (USER/SCANNER account in WEB)

### ISSUE THREAD

**Issue by Claire-pn** [kennCK/tinabangay_app#9]
Test case:
Clicking the logout tab

Remarks:
--this appears first before the home page 
--it doesnt redirect to home page

![image](https://user-images.githubusercontent.com/54086974/88353457-159fcb80-cd90-11ea-8fea-ce386e5e2bdf.png)

**Comment by kennCK** [comment]
@Claire-pn closing this as this belongs to the [tinabangay](https://github.com/kennCK/tinabangay)
